![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# Pandas Series exercises

In [1]:
# Import the numpy package under the name np
import numpy as np

# Import the pandas package under the name pd
import pandas as pd

# Print the pandas version and the configuration
print(pd.__version__)

2.2.2

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series creation

### Create an empty pandas Series

In [2]:
# your code goes here
pd.Series()

Series([], dtype: object)

In [ ]:
pd.Series()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y pandas Series

In [3]:
# your code goes here
X = ['A','B', 'C']
print(X, type(X))

Y = pd.Series(X)
print(Y, type(Y))

['A', 'B', 'C'] <class 'list'>
0    A
1    B
2    C
dtype: object <class 'pandas.core.series.Series'>

In [4]:
X = ['A','B','C']
print(X, type(X))

Y = pd.Series(X)
print(Y, type(Y)) # different type

['A', 'B', 'C'] <class 'list'>
0    A
1    B
2    C
dtype: object <class 'pandas.core.series.Series'>

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, name it 'My letters'

In [6]:
# your code goes here
X = pd.Series(['A','B','C'])
X.name = 'My letters'
X

0    A
1    B
2    C
Name: My letters, dtype: object

In [ ]:
X = pd.Series(['A','B','C'])

X.name = 'My letters'
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its values

In [7]:
# your code goes here
X = pd.Series(['A','B','C'])
X.values

array(['A', 'B', 'C'], dtype=object)

In [ ]:
X = pd.Series(['A','B','C'])

X.values

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series indexation

### Assign index names to the given X pandas Series

In [8]:
# your code goes here
X = pd.Series(['A','B','C'])
index_names = ['first', 'second', 'third']
X.index = index_names
X

first     A
second    B
third     C
dtype: object

In [ ]:
X = pd.Series(['A','B','C'])
index_names = ['first', 'second', 'third']

X.index = index_names
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its first element

In [9]:
# your code goes here
X = pd.Series(['A', 'B', 'C'], index=['first', 'second', 'third'])
X['first']

'A'

In [ ]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])

#X[0] # by position
#X.iloc[0] # by position
X['first'] # by index

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its last element

In [12]:
# your code goes here
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])
# X.iloc[-1]
X['third']

'C'

In [13]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])

#X[-1] # by position
#X.iloc[-1] # by position
X['third'] # by index

'C'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show all middle elements

In [19]:
# your code goes here
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])
X.iloc[1:-1]
# X[1:-1]

second    B
third     C
forth     D
dtype: object

In [ ]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['second', 'third', 'forth']]
#X.iloc[1:-1] # by position
X[1:-1] # by position

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the elements in reverse position

In [20]:
# your code goes here
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])
X.iloc[::-1]

fifth     E
forth     D
third     C
second    B
first     A
dtype: object

In [21]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X.iloc[::-1]
X[::-1]

fifth     E
forth     D
third     C
second    B
first     A
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the first and last elements

In [22]:
# your code goes here
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])
X.iloc[[0, -1]]

first    A
fifth    E
dtype: object

In [ ]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['first', 'fifth']]
#X.iloc[[0, -1]]
X[[0, -1]]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series manipulation

### Convert the given integer pandas Series to float

In [23]:
# your code goes here
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])
pd.Series(X, dtype=float)

first     1.0
second    2.0
third     3.0
forth     4.0
fifth     5.0
dtype: float64

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

pd.Series(X, dtype=np.float)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given pandas Series (first element becomes last)

In [24]:
# your code goes here
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])
X[::-1]

fifth     5
forth     4
third     3
second    2
first     1
dtype: int64

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given pandas Series

In [25]:
# your code goes here
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])
X = X.sort_values()
X

first     1
second    2
third     3
forth     4
fifth     5
dtype: int64

In [26]:
X = pd.Series([4,2,5,1,3],
              index=['forth','second','fifth','first','third'])

X = X.sort_values()
X

first     1
second    2
third     3
forth     4
fifth     5
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, set the fifth element equal to 10

In [30]:
# your code goes here
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])
# X[4] = 10
X.iloc[:-1] = 10

X

first     10
second    10
third     10
forth     10
fifth      5
dtype: int64

In [31]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[4] = 10
X

/tmp/ipykernel_15251/4063770036.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  X[4] = 10

A     1
B     2
C     3
D     4
E    10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, change all the middle elements to 0

In [33]:
# your code goes here
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])
# X[1:-1] = 0
X.iloc[1:-1] = 0
X

first     1
second    0
third     0
forth     0
fifth     5
dtype: int64

In [34]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[1:-1] = 0
X

A    1
B    0
C    0
D    0
E    5
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, add 5 to every element

In [35]:
# your code goes here
X = pd.Series([1,2,3,4,5])
X + 5

0     6
1     7
2     8
3     9
4    10
dtype: int64

In [ ]:
X = pd.Series([1,2,3,4,5])

X + 5

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series boolean arrays (also called masks)

### Given the X pandas Series, make a mask showing negative elements

In [36]:
# your code goes here
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
mask

0     True
1    False
2     True
3     True
4    False
5    False
6     True
7     True
8     True
9    False
dtype: bool

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get the negative elements

In [37]:
# your code goes here
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
X[mask]

0   -1
2    0
3   -4
6    0
7    0
8   -9
dtype: int64

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than 5

In [38]:
# your code goes here
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
mask = X >=5
X[mask]

4     5
5     6
9    10
dtype: int64

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > 5
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than the elements mean

In [39]:
# your code goes here
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
mask = X > X.mean()
X[mask]

1     2
4     5
5     6
9    10
dtype: int64

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > X.mean()
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers equal to 2 or 10

In [40]:
# your code goes here
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
mask = (X == 2) | (X == 10)
X[mask]

1     2
9    10
dtype: int64

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = (X == 2) | (X == 10)
X[mask]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions

### Given the X pandas Series, return True if none of its elements is zero

In [41]:
# your code goes here
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
X.all()

np.False_

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.all()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, return True if any of its elements is zero

In [42]:
# your code goes here
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
X.any()

np.True_

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.any()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X pandas Series, show the sum of its elements

In [48]:
# your code goes here
X = pd.Series([3,5,6,7,2,3,4,9,4])
X.sum()
# np.sum(X)

np.int64(43)

In [47]:
X = pd.Series([3,5,6,7,2,3,4,9,4])

# np.sum(X)
X.sum()

np.int64(43)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the mean value of its elements

In [49]:
# your code goes here
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

X.mean()

np.float64(3.7)

In [ ]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.mean(X)
X.mean()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the max value of its elements

In [50]:
# your code goes here
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

X.max()

10

In [ ]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.max(X)
X.max()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)